spring:
  profiles:
    include:
      core
    active: dev
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_KEY}
            scope:
              - email
              - profile
