### 로그인상태에서의 메인페이지 조회
GET http://localhost:8080/accommodation?category=HOTEL&isDomestic=true&page=0&startDate=2023-11-02&endDate=2023-11-08&numberOfPeople=2
Authorization: token

### 로그인 없이 메인페이지 조회
GET http://localhost:8080/accommodation?category=HOTEL&isDomestic=true&page=0&startDate=2023-11-02&endDate=2023-11-08&numberOfPeople=2

